### ISSUE TITLE
Set up CI/CD pipeline with GitHub Actions

### ISSUE THREAD

**Issue by MK-ayaz** [MK-ayaz/realtime-chat-nextjs-app#2]
## CI/CD Pipeline Setup

We need to set up a CI/CD pipeline using GitHub Actions to automate testing, building, and deployment processes.

### Tasks

1. Create GitHub Actions workflow:
```yaml
name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: chat_app_test
        ports:
          - 5432:5432
        options: >
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Setup environment variables
      run: |
        echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/chat_app_test?schema=public" >> .env
        echo "NEXTAUTH_SECRET=test-secret" >> .env
        echo "NEXTAUTH_URL=http://localhost:3000" >> .env

    - name: Run database migrations
      run: npx prisma migrate deploy

    - name: Run linting
      run: npm run lint

    - name: Run type checking
      run: npx tsc --noEmit

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build
```

2. Configure repository secrets:
   - [ ] Add `DATABASE_URL` secret
   - [ ] Add `NEXTAUTH_SECRET` secret
   - [ ] Add deployment-related secrets

3. Set up deployment:
   - [ ] Configure deployment to Vercel/Railway/etc.
   - [ ] Set up automatic deployments on successful builds
   - [ ] Configure preview deployments for pull requests

4. Add status badges:
   - [ ] Add CI/CD status badge to README
   - [ ] Add code coverage badge
   - [ ] Add dependency status badge

5. Documentation:
   - [ ] Document CI/CD process
   - [ ] Add deployment instructions
   - [ ] Update contribution guidelines

### Additional Considerations

1. Test coverage requirements
2. Performance benchmarks
3. Security scanning
4. Dependency updates
5. Environment-specific configurations
